name: Scheduled Health Check

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:      # permite lanzarlo manualmente también

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    permissions:
      contents: write   # necesario para hacer git commit + push
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./health-check.sh

      - name: Run Health Check
        run: ./health-check.sh
